#!/bin/bash

remove() {
	echo "removing '$1'"
	rm -f "$1"	
}

for I in ./examples/basic_arithmetic/basic_arithmetic.grammar.inc.h.bak*; do
	remove $I
done
for I in ./src/glanguage/g.grammar.inc.h.bak*; do
	remove $I
done
