// This file is generated by 
//       https://github.com/IDNI/parser/tools/tgf
#include <string.h>
#include "parser.h"
struct csv_parser {
	csv_parser() :
		nts(load_nonterminals()), cc(load_cc()),
		g(nts, load_prods(), nt(25), cc), p(g, load_opts()) {}
	std::unique_ptr<typename idni::parser<char, char>::pforest> parse(
		const char* data, size_t size = 0,
		char eof = std::char_traits<char>::eof())
			{ return p.parse(data, size, eof); }
	std::unique_ptr<typename idni::parser<char, char>::pforest> parse(
		int fd, size_t size = 0,
		char eof = std::char_traits<char>::eof())
			{ return p.parse(fd, size, eof); }
	std::unique_ptr<typename idni::parser<char, char>::pforest> parse(
		std::basic_istream<char>& is,
		size_t size = 0,
		char eof = std::char_traits<char>::eof())
			{ return p.parse(is, size, eof); }
	bool found() { return p.found(); }
	typename idni::parser<char, char>::error get_error()
		{ return p.get_error(); }
	size_t id(const std::basic_string<char>& name) { return nts.get(name); }
private:
	std::vector<char> ts{
		'\0', '-', '"', '\\', '\r', '\n', ',', 
	};
	idni::nonterminals<char, char> nts{};
	idni::char_class_fns<char> cc;
	idni::grammar<char, char> g;
	idni::parser<char, char> p;
	idni::prods<char, char> t(size_t tid) {
		return idni::prods<char, char>(ts[tid]);
	}
	idni::prods<char, char> nt(size_t ntid) {
		return idni::prods<char, char>(idni::lit<char, char>(ntid, &nts));
	}
	idni::nonterminals<char, char> load_nonterminals() const {
		idni::nonterminals<char, char> nts{};
		for (const auto& nt : {
			"", "digit", "printable", "integer", "integer_0", "integer_1", "quote", "esc", "quoted", "unescaped", 
			"escaped", "strchar", "str", "str_2", "str_3", "nullvalue", "val", "eol", "eol_4", "row", 
			"row_5", "row_6", "rows", "rows_7", "rows_8", "start", "__neg_0", 
		}) nts.get(nt);
		return nts;
	}
	idni::char_class_fns<char> load_cc() {
		return idni::predefined_char_classes<char, char>({
			"digit",
			"printable",
		}, nts);
	}
	idni::parser<char, char>::options load_opts() {
		idni::parser<char, char>::options o;
		return o;
	}
	idni::prods<char, char> load_prods() {
		idni::prods<char, char> q, nul(idni::lit<char, char>{});
		// integer_0 => ε.
		q(nt(4), (nul));
		// integer_0 => '-'.
		q(nt(4), (t(1)));
		// integer_1 => digit.
		q(nt(5), (nt(1)));
		// integer_1 => digit integer_1.
		q(nt(5), (nt(1)+nt(5)));
		// integer => integer_0 integer_1.
		q(nt(3), (nt(4)+nt(5)));
		// quote => '"'.
		q(nt(6), (t(2)));
		// esc => '\\'.
		q(nt(7), (t(3)));
		// quoted => quote.
		q(nt(8), (nt(6)));
		// quoted => esc.
		q(nt(8), (nt(7)));
		// __neg_0 => quoted.
		q(nt(26), (nt(8)));
		// unescaped => printable & ~( __neg_0 ).
		q(nt(9), (nt(2)) & ~(nt(26)));
		// escaped => esc quoted.
		q(nt(10), (nt(7)+nt(8)));
		// strchar => unescaped.
		q(nt(11), (nt(9)));
		// strchar => escaped.
		q(nt(11), (nt(10)));
		// str_2 => strchar str_2.
		q(nt(13), (nt(11)+nt(13)));
		// str_2 => ε.
		q(nt(13), (nul));
		// str_3 => str_2.
		q(nt(14), (nt(13)));
		// str => quote str_3 quote.
		q(nt(12), (nt(6)+nt(14)+nt(6)));
		// nullvalue => ε.
		q(nt(15), (nul));
		// val => integer.
		q(nt(16), (nt(3)));
		// val => str.
		q(nt(16), (nt(12)));
		// val => nullvalue.
		q(nt(16), (nt(15)));
		// eol_4 => ε.
		q(nt(18), (nul));
		// eol_4 => '\r'.
		q(nt(18), (t(4)));
		// eol => eol_4 '\n'.
		q(nt(17), (nt(18)+t(5)));
		// row_5 => ',' val.
		q(nt(20), (t(6)+nt(16)));
		// row_6 => row_5 row_6.
		q(nt(21), (nt(20)+nt(21)));
		// row_6 => ε.
		q(nt(21), (nul));
		// row => val row_6.
		q(nt(19), (nt(16)+nt(21)));
		// rows_7 => eol row.
		q(nt(23), (nt(17)+nt(19)));
		// rows_8 => rows_7 rows_8.
		q(nt(24), (nt(23)+nt(24)));
		// rows_8 => ε.
		q(nt(24), (nul));
		// rows => row rows_8.
		q(nt(22), (nt(19)+nt(24)));
		// start => rows.
		q(nt(25), (nt(22)));
		return q;
	}
};
