#
# CPack configuration
#

set(CPACK_PACKAGE_NAME "${PROJECT_NAME}")
set(CPACK_PACKAGE_VERSION "${TAU_PARSER_VERSION}")
set(CPACK_PACKAGE_FILE_NAME "lib${CPACK_PACKAGE_NAME}-${CPACK_PACKAGE_VERSION}")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "${PROJECT_DESCRIPTION}")
set(CPACK_PACKAGE_VENDOR "IDNI")
set(CPACK_PACKAGE_CONTACT "contact@idni.org")
set(CPACK_PACKAGE_DIRECTORY "${CMAKE_BINARY_DIR}/packages")
set(CPACK_PACKAGE_HOMEPAGE_URL "https://idni.org")
set(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_CURRENT_SOURCE_DIR}/LICENSE.txt")
set(CPACK_RESOURCE_FILE_README "${CMAKE_CURRENT_SOURCE_DIR}/README.md")
set(CPACK_COMPONENT_INCLUDE_TOPLEVEL_DIRECTORY OFF)

#
# Specify installation directories and files
#
if (TAU_PARSER_WINDOWS_PACKAGE)
	set(CPACK_GENERATOR "NSIS")
	# NSIS (Windows Installer) specific settings
	set(CPACK_NSIS_FILE_NAME "${CPACK_PACKAGE_FILE_NAME}.exe")
	set(CPACK_PACKAGE_INSTALL_DIRECTORY "tauparser-${CPACK_PACKAGE_VERSION}")
	set(CPACK_NSIS_DISPLAY_NAME "Tau Parser Library")
	set(CPACK_NSIS_HELP_LINK "https://github.com/IDNI/parser/blob/main/README.md")
	set(CPACK_NSIS_URL_INFO_ABOUT "${CPACK_PACKAGE_HOMEPAGE_URL}")
	set(CPACK_NSIS_CONTACT "${CPACK_PACKAGE_CONTACT}")
	set(CPACK_NSIS_LICENSE_FILE "${CMAKE_SOURCE_DIR}/LICENSE.txt")
	set(CPACK_NSIS_INSTALLER_PRIVILEGES "lowest")
	set(CPACK_NSIS_MODIFY_PATH ON)
	set(CPACK_NSIS_EXECUTABLES_DIRECTORY "${TAU_PARSER_BIN_DESTINATION}")
	set(CPACK_NSIS_MENU_LINKS "${TAU_PARSER_BIN_DESTINATION}/tgf.exe" "TGF Tool")
elseif (TAU_PARSER_WINDOWS_ZIP_PACKAGE)
	set(CPACK_GENERATOR "ZIP")
	set(CPACK_ARCHIVE_COMPONENT_INSTALL OFF)
else()
	set(CPACK_GENERATOR "DEB;RPM")
	# DEB specific settings
	set(CPACK_DEBIAN_PACKAGE_FILE_NAME "${CPACK_PACKAGE_FILE_NAME}.deb")
	set(CPACK_DEBIAN_PACKAGE_MAINTAINER "IDNI")
	set(CPACK_DEBIAN_PACKAGE_DEPENDS "libc6 (>= 2.27)")
	set(CPACK_DEBIAN_PACKAGE_SECTION "devel")
	set(CPACK_DEBIAN_ARCHITECTURE "amd64")
	# RPM specific settings
	set(CPACK_RPM_PACKAGE_FILE_NAME "${CPACK_PACKAGE_FILE_NAME}.rpm")
	set(CPACK_RPM_PACKAGE_AUTOREQ " no")
	set(CPACK_RPM_PACKAGE_ARCHITECTURE "x86_64")
	set(CPACK_RPM_PACKAGE_LICENSE "Tau Parser Library")
	set(CPACK_RPM_PACKAGE_GROUP "Development/Tools")
	#set(CPACK_RPM_PACKAGE_REQUIRES "libc >= 2.27")
	set(CPACK_RPM_PACKAGE_DOC_DIR "share/doc/${PROJECT_NAME}")
endif()

if(TAU_PARSER_WINDOWS_ZIP_PACKAGE OR TAU_PARSER_WINDOWS_PACKAGE)
	set(CPACK_COMPONENTS_ALL "tgf" "Documentation" "Examples" "Library")
else()
	set(CPACK_COMPONENTS_ALL "tgf" "Documentation" "Examples" "cmake")
endif()

# Include the CPack module
include(CPack)
