if(NOT ICECC_BINARY)
	find_program(ICECC_BINARY icecc)
endif()
if(ICECC_BINARY)
	set(CMAKE_C_COMPILER_LAUNCHER   "${ICECC_BINARY}" CACHE STRING "C compiler launcher (icecc)")
	set(CMAKE_CXX_COMPILER_LAUNCHER "${ICECC_BINARY}" CACHE STRING "C++ compiler launcher (icecc)")
	message(STATUS "Using icecream: ${ICECC_BINARY}")
else()
	message(WARNING "icecc not found")
endif()
